source 'https://rubygems.org'
Encoding.default_external = Encoding::UTF_8
ruby '~> 2.7.0'

gem 'activesupport'
gem 'bundler'
gem 'cucumber', '~> 7.1'
gem 'cuke_modeler'
gem 'documentos_br'
gem 'excon'
gem 'down'
gem 'faker'
gem 'json'
gem 'net-sftp'
gem 'nokogiri'
gem 'os'
gem 'parallel_tests'
gem 'rack', '~> 2.2.4'
gem 'rake'
gem 'regexp_parser', '2.3.0'
gem 'report_builder'
gem 'rspec', '3.10.0'
gem 'rubocop-checkstyle_formatter'
gem 'savon'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'cpf_faker'
gem 'dbi'
gem 'faraday'
gem 'faraday_middleware'
gem 'holidays'
gem 'httparty'
gem 'mime-types'
gem 'net-ssh'
gem 'ruby-oci8'
gem 'write_xlsx'
gem 'appium_lib', '~> 11.2'
gem 'percentage'
gem 'touch_action'

gem 'ffi' if Gem.win_platform?

group :development do
  gem 'pry'
end
